version: "3"
services:
  web:
    build: .
    ports:
      - "8080:9876"
    links:
      - mongo
    environment:
      PORT : 9876
      MONGO_URL : "mongodb://mongo:27017/armut-app"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
